//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string BooksView_AvailabilityAll {
            get {
                return ResourceManager.GetString("BooksView_AvailabilityAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string BooksView_AvailabilityAvailable {
            get {
                return ResourceManager.GetString("BooksView_AvailabilityAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string BooksView_AvailabilityUnavailable {
            get {
                return ResourceManager.GetString("BooksView_AvailabilityUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by id, title, author, publisher or release date..
        /// </summary>
        public static string BooksView_searchBoxDefaultText {
            get {
                return ResourceManager.GetString("BooksView_searchBoxDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all parameters.
        /// </summary>
        public static string BooksView_SearchOptions_AllParameters {
            get {
                return ResourceManager.GetString("BooksView_SearchOptions_AllParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search author.
        /// </summary>
        public static string BooksView_SearchOptions_Author {
            get {
                return ResourceManager.GetString("BooksView_SearchOptions_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search id.
        /// </summary>
        public static string BooksView_SearchOptions_Id {
            get {
                return ResourceManager.GetString("BooksView_SearchOptions_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search publisher.
        /// </summary>
        public static string BooksView_SearchOptions_Publisher {
            get {
                return ResourceManager.GetString("BooksView_SearchOptions_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search release date.
        /// </summary>
        public static string BooksView_SearchOptions_ReleaseDate {
            get {
                return ResourceManager.GetString("BooksView_SearchOptions_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search title.
        /// </summary>
        public static string BooksView_SearchOptions_Title {
            get {
                return ResourceManager.GetString("BooksView_SearchOptions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display available:.
        /// </summary>
        public static string BooksView_showAvailableLabel {
            get {
                return ResourceManager.GetString("BooksView_showAvailableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SchoolLibrary {
            get {
                object obj = ResourceManager.GetObject("SchoolLibrary", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
